from django.urls import path

from . import views

app_name = 'sources'
urlpatterns = [
	path('',views.home, name='home'),
	path('home/',views.home, name='home'),
	path('detail_infographic_view/<int:pk>',views.detail_infographic_view, 
		name='detail_infographic_view'),
	path('detail_artefact_view/<int:pk>',views.detail_artefact_view, 
		name='detail_artefact_view'),
	path('detail_videogame_view/<int:pk>',views.detail_videogame_view, 
		name='detail_videogame_view'),
	path('detail_recordedspeech_view/<int:pk>',views.detail_recordedspeech_view, 
		name='detail_recordedspeech_view'),
	path('detail_memorialsite_view/<int:pk>',views.detail_memorialsite_view, 
		name='detail_memorialsite_view'),
	path('detail_picturestory_view/<int:pk>',views.detail_picturestory_view, 
		name='detail_picturestory_view'),
	path('detail_image_view/<int:pk>',views.detail_image_view, 
		name='detail_image_view'),
	path('detail_film_view/<int:pk>',views.detail_film_view, 
		name='detail_film_view'),
	path('detail_music_view/<int:pk>',views.detail_music_view, 
		name='detail_music_view'),
	path('detail_text_view/<int:pk>',views.detail_text_view, 
		name='detail_text_view'),
	path('add_videogame/',views.edit_videogame, name='add_videogame'),
	path('add_memorialsite/',views.edit_memorialsite, name='add_memorialsite'),
	path('add_recordedspeech/',views.edit_recordedspeech, 
		name='add_recordedspeech'),
	path('add_film/',views.edit_film, name='add_film'),
	path('add_text/',views.edit_text, name='add_text'),
	path('add_music/',views.edit_music, name='add_music'),
	path('add_infographic/',views.edit_infographic, name='add_infographic'),
	path('add_image/',views.edit_image, name='add_image'),
	path('add_artefact/',views.edit_artefact, name='add_artefact'),
	path('add_picture_story/',views.edit_picture_story, 
		name='add_picture_story'),
	path('add_picturestory/',views.edit_picture_story, name='add_picturestory'),
	path('add_picture_story_type/',views.add_picture_story_type, 
		name='add_picture_story_type'),
	path('add_picture_story_type/<int:pk>',views.add_picture_story_type, 
		name='add_picture_story_type'),
	path('add_publishing_outlet/',views.add_publishing_outlet, 
		name='add_publishing_outlet'),
	path('add_publishing_outlet/<int:pk>',views.add_publishing_outlet, 
		name='add_publishing_outlet'),
	path('add_image_type/',views.add_image_type, name='add_image_type'),
	path('add_image_type/<int:pk>',views.add_image_type, name='add_image_type'),
	path('add_artefact_type/',views.add_artefact_type, name='add_artefact_type'),
	path('add_artefact_type/<int:pk>',views.add_artefact_type, 
		name='add_artefact_type'),
	path('add_text_type/',views.add_text_type, name='add_text_type'),
	path('add_text_type/<int:pk>',views.add_text_type, name='add_text_type'),
	path('add_music_type/',views.add_music_type, name='add_music_type'),
	path('add_music_type/<int:pk>',views.add_music_type, name='add_music_type'),
	path('add_game_type/',views.add_game_type, name='add_game_type'),
	path('add_game_type/<int:pk>',views.add_game_type, name='add_game_type'),
	path('add_memorial_type/',views.add_memorial_type, name='add_memorial_type'),
	path('add_memorial_type/<int:pk>',views.add_memorial_type, 
		name='add_memorial_type'),
	path('add_recordedspeech_type/',views.add_recordedspeech_type, 
		name='add_recordedspeech_type'),
	path('add_recordedspeech_type/<int:pk>',views.add_recordedspeech_type, 
		name='add_recordedspeech_type'),
	path('add_film_type/',views.add_film_type, name='add_film_type'),
	path('add_film_type/<int:pk>',views.add_film_type, name='add_film_type'),
	path('add_infographic_type/',views.add_infographic_type, 
		name='add_infographic_type'),
	path('add_infographic_type/<int:pk>',views.add_infographic_type, 
		name='add_infographic_type'),
	path('add_film_company/',views.add_film_company, name='add_film_company'),
	path('add_film_company/<int:pk>',views.add_film_company, 
		name='add_film_company'),
	path('add_production_studio/',views.add_production_studio, 
		name='add_production_studio'),
	path('add_production_studio/<int:pk>',views.add_production_studio, 
		name='add_production_studio'),
	path('add_broadcasting_station/',views.add_broadcasting_station, 
		name='add_broadcasting_station'),
	path('add_broadcasting_station/<int:pk>',views.add_broadcasting_station, 
		name='add_broadcasting_station'),
	path('add_institution/',views.add_institution, name='add_institution'),
	path('add_institution/<int:pk>',views.add_institution, 
		name='add_institution'),
	path('add_publisher/',views.add_publisher, name='add_publisher'),
	path('add_publisher/<int:pk>',views.add_publisher, name='add_publisher'),
	path('add_target_audience/',views.add_target_audience, 
		name='add_target_audience'),
	path('add_target_audience/<int:pk>',views.add_target_audience, 
		name='add_target_audience'),
	path('add_collection/',views.add_collection, name='add_collection'),
	path('add_collection/<int:pk>',views.add_collection, name='add_collection'),
	path('music/',views.view_list,{'name':'Music'}, name='music'),
	path('film/',views.view_list,{'name':'Film'}, name='film'),
	path('text/',views.view_list,{'name':'Text'}, name='text'),
	path('image/',views.view_list,{'name':'Image'}, name='image'),
	path('infographic/',views.view_list,{'name':'Infographic'}, 
		name='infographic'),
	path('PictureStory/',views.view_list,{'name':'PictureStory'}, 
		name='picturestory'),
	path('artefact/',views.view_list,{'name':'Artefact'}, name='artefact'),
	path('edit_film/<int:pk>/',views.edit_film, name='edit_film'),
	path('edit_film/<int:pk>/<str:focus>/',views.edit_film, name='edit_film'),
	path('edit_memorialsite/<int:pk>/',views.edit_memorialsite, 
		name='edit_memorialsite'),
	path('edit_memorialsite/<int:pk>/<str:focus>/',views.edit_memorialsite, 
		name='edit_memorialsite'),
	path('edit_videogame/<int:pk>/',views.edit_videogame, name='edit_videogame'),
	path('edit_videogame/<int:pk>/<str:focus>/',views.edit_videogame, 
		name='edit_videogame'),
	path('edit_recordedspeech/<int:pk>/',views.edit_recordedspeech, 
		name='edit_recordedspeech'),
	path('edit_recordedspeech/<int:pk>/<str:focus>/',views.edit_recordedspeech, 
		name='edit_recordedspeech'),
	path('edit_text/<int:pk>/',views.edit_text, name='edit_text'),
	path('edit_text/<int:pk>/<str:focus>/',views.edit_text, name='edit_text'),
	path('edit_music/<int:pk>/',views.edit_music, name='edit_music'),
	path('edit_music/<int:pk>/<str:focus>/',views.edit_music, name='edit_music'),
	path('edit_image/<int:pk>/',views.edit_image, name='edit_image'),
	path('edit_image/<int:pk>/<str:focus>/',views.edit_image, name='edit_image'),
	path('edit_artefact/<int:pk>/',views.edit_artefact, name='edit_artefact'),
	path('edit_artefact/<int:pk>/<str:focus>/',views.edit_artefact, 
		name='edit_artefact'),
	path('edit_infographic/<int:pk>/',views.edit_infographic, 
		name='edit_infographic'),
	path('edit_infographic/<int:pk>/<str:focus>/',views.edit_infographic,
		name='edit_infographic'),
	path('edit_picture_story/<int:pk>/',views.edit_picture_story, 
		name='edit_picture_story'),
	path('edit_picture_story/<int:pk>/<str:focus>/',views.edit_picture_story,
		name='edit_picture_story'),
	path('edit_picturestory/<int:pk>/',views.edit_picture_story, 
		name='edit_picturestory'),
	path('edit_picture_story/<int:pk>/<str:focus>/',views.edit_picture_story, 
		name='edit_picturestory'),
	path('delete/<int:pk>/<str:model_name>',views.delete,name='delete'),
]
