# Generated by Django 2.2.13 on 2020-07-16 15:20

from django.db import migrations, models
import utils.model_util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CausalTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamineName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iso', models.CharField(blank=True, max_length=3, null=True)),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='Famine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_excess_mortality', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(default='')),
                ('comments', models.TextField(default='')),
                ('causal_triggers', models.ManyToManyField(blank=True, related_name='famine_causal_triggers', to='misc.CausalTrigger')),
                ('keywords', models.ManyToManyField(blank=True, to='misc.Keyword')),
                ('locations', models.ManyToManyField(blank=True, related_name='famine_locations', to='locations.Location')),
                ('names', models.ManyToManyField(blank=True, to='misc.FamineName')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
    ]
