# Generated by Django 2.2.13 on 2020-07-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causaltrigger',
            name='name',
            field=models.CharField(default='', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='faminename',
            name='name',
            field=models.CharField(default='', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(default='', max_length=300, unique=True),
        ),
    ]
