# Generated by Django 2.2.10 on 2020-07-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='keywords',
        ),
        migrations.AddField(
            model_name='person',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='persons.Keyword'),
        ),
    ]
