# Generated by Django 2.2.10 on 2020-06-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commisioner',
            new_name='Commissioner',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='requist_use_permission',
            new_name='request_use_permission',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='requist_use_permission',
            new_name='request_use_permission',
        ),
        migrations.RenameField(
            model_name='infographic',
            old_name='requist_use_permission',
            new_name='request_use_permission',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='requist_use_permission',
            new_name='request_use_permission',
        ),
        migrations.RenameField(
            model_name='picturestory',
            old_name='requist_use_permission',
            new_name='request_use_permission',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='requist_use_permission',
            new_name='request_use_permission',
        ),
    ]
