# Generated by Django 2.2.10 on 2020-06-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_auto_20200619_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
