# Generated by Django 2.2.10 on 2020-06-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_simplemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleModel',
        ),
    ]
