# Generated by Django 2.2.10 on 2020-06-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_auto_20200619_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='composer',
        ),
        migrations.AddField(
            model_name='music',
            name='composer',
            field=models.ManyToManyField(blank=True, related_name='music_composer', to='sources.Person'),
        ),
    ]
