# Generated by Django 2.2.10 on 2020-06-24 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0007_auto_20200624_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='composer',
            new_name='composers',
        ),
    ]
