# Generated by Django 2.2.10 on 2020-06-24 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0008_auto_20200624_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestUsePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='film',
            name='location_released',
        ),
        migrations.RemoveField(
            model_name='film',
            name='location_shot',
        ),
        migrations.AddField(
            model_name='film',
            name='locations_released',
            field=models.ManyToManyField(blank=True, related_name='film_location_released', to='sources.Location'),
        ),
        migrations.AddField(
            model_name='film',
            name='locations_shot',
            field=models.ManyToManyField(blank=True, related_name='film_location_shot', to='sources.Location'),
        ),
        migrations.AlterField(
            model_name='film',
            name='request_use_permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.RequestUsePermission'),
        ),
        migrations.AlterField(
            model_name='image',
            name='request_use_permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.RequestUsePermission'),
        ),
        migrations.AlterField(
            model_name='infographic',
            name='request_use_permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.RequestUsePermission'),
        ),
        migrations.AlterField(
            model_name='music',
            name='request_use_permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.RequestUsePermission'),
        ),
        migrations.AlterField(
            model_name='picturestory',
            name='request_use_permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.RequestUsePermission'),
        ),
        migrations.AlterField(
            model_name='text',
            name='request_use_permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.RequestUsePermission'),
        ),
    ]
