# Generated by Django 2.2.10 on 2020-06-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0009_auto_20200624_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infographic',
            name='creator',
        ),
        migrations.AddField(
            model_name='infographic',
            name='creators',
            field=models.ManyToManyField(blank=True, related_name='infographic_creators', to='sources.Person'),
        ),
    ]
