# Generated by Django 2.2.10 on 2020-06-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0010_auto_20200625_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='creator',
        ),
        migrations.AddField(
            model_name='image',
            name='creators',
            field=models.ManyToManyField(blank=True, related_name='image_creators', to='sources.Person'),
        ),
    ]
