# Generated by Django 2.2.10 on 2020-06-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0011_auto_20200625_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
        migrations.AddField(
            model_name='image',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='image_locations', to='sources.Location'),
        ),
    ]
