# Generated by Django 2.2.10 on 2020-07-01 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
        ('sources', '0012_auto_20200625_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picturestory',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='picturestory',
            name='author',
        ),
        migrations.RemoveField(
            model_name='picturestory',
            name='translator',
        ),
        migrations.AddField(
            model_name='picturestory',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='picture_story_artist', to='persons.Person'),
        ),
        migrations.AddField(
            model_name='picturestory',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='picture_story_author', to='persons.Person'),
        ),
        migrations.AddField(
            model_name='picturestory',
            name='translators',
            field=models.ManyToManyField(blank=True, related_name='picture_story_translator', to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='film',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='film_directors', to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='film',
            name='writers',
            field=models.ManyToManyField(blank=True, related_name='film_writers', to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='image',
            name='creators',
            field=models.ManyToManyField(blank=True, related_name='image_creators', to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='infographic',
            name='creators',
            field=models.ManyToManyField(blank=True, related_name='infographic_creators', to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='music',
            name='composers',
            field=models.ManyToManyField(blank=True, related_name='music_composer', to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='text',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_author', to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='text',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_editor', to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='text',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_translator', to='persons.Person'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
