# Generated by Django 2.2.10 on 2020-07-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0013_auto_20200701_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='keywords',
        ),
        migrations.AddField(
            model_name='film',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='sources.Keyword'),
        ),
        migrations.RemoveField(
            model_name='image',
            name='keywords',
        ),
        migrations.AddField(
            model_name='image',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='sources.Keyword'),
        ),
        migrations.RemoveField(
            model_name='infographic',
            name='keywords',
        ),
        migrations.AddField(
            model_name='infographic',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='sources.Keyword'),
        ),
        migrations.RemoveField(
            model_name='music',
            name='keywords',
        ),
        migrations.AddField(
            model_name='music',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='sources.Keyword'),
        ),
        migrations.RemoveField(
            model_name='picturestory',
            name='keywords',
        ),
        migrations.AddField(
            model_name='picturestory',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='sources.Keyword'),
        ),
        migrations.RemoveField(
            model_name='text',
            name='keywords',
        ),
        migrations.AddField(
            model_name='text',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='sources.Keyword'),
        ),
    ]
