# Generated by Django 2.2.13 on 2020-07-16 15:20

from django.db import migrations, models
import django.db.models.deletion
import utils.model_util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('geonameid', models.CharField(default='', max_length=12, unique=True)),
                ('coordinates_polygon', models.CharField(blank=True, max_length=3000, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('information', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='LocationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contained', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contained', to='locations.Location')),
                ('container', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='container', to='locations.Location')),
            ],
            options={
                'unique_together': {('container', 'contained')},
            },
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.LocationType'),
        ),
        migrations.AddField(
            model_name='location',
            name='relations',
            field=models.ManyToManyField(default=None, through='locations.LocationRelation', to='locations.Location'),
        ),
    ]
