# Generated by Django 2.2.13 on 2020-07-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20200717_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationprecision',
            name='name',
            field=models.CharField(default='', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='locationstatus',
            name='name',
            field=models.CharField(default='', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='locationtype',
            name='name',
            field=models.CharField(default='', max_length=300, unique=True),
        ),
    ]
